volumes:
  dvwa:

networks:
  dvwa:

services:
  dvwa:
    build: .
    image: ghcr.io/digininja/dvwa:latest
    # Change `always` to `build` to build from local source
    pull_policy: always
    environment:
      - DB_SERVER=db
      - DB_USER=${DVWA_DB_USER:-dvwa}
      - DB_PASSWORD=${DVWA_DB_PASSWORD}        # Mot de passe défini dans le fichier .env
      - DB_NAME=${DVWA_DB_NAME:-dvwa}
    depends_on:
      - db
    networks:
      - dvwa
    ports:
      - 127.0.0.1:4280:80
    restart: unless-stopped

  db:
    image: docker.io/library/mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}   # À définir dans .env
      - MYSQL_DATABASE=${DVWA_DB_NAME:-dvwa}
      - MYSQL_USER=${DVWA_DB_USER:-dvwa}
      - MYSQL_PASSWORD=${DVWA_DB_PASSWORD}           # À définir dans .env
    volumes:
      - dvwa:/var/lib/mysql
    networks:
      - dvwa
    restart: unless-stopped
